### ISSUE TITLE
Move questions 2 & 3  to Colab notebook

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss-labs/rialto-scripts#22]
Questions 2 and 3 both deal with Open Access publication trends; it makes sense to group them in one Colab notebook.

The initial questions from Rochelle are [here](https://docs.google.com/document/d/1VQooV2hzN0q_HYJQClPQh5rKPZLr00jd-jsIOSxNDcE/edit#heading=h.irycl3fvo3cl).

The dashboard pages that try to answer those questions are 4 and 5  [here](https://sul-dlss-labs-rialto-scripts-oa-dashboardoa-dashboard-yiuiox.streamlit.app/).

You can work in [this notebook](https://colab.research.google.com/drive/1R2OOtm1iwgmO_ZohopFqptBGBBHlW8a8).

The starting data file is [here](https://drive.google.com/drive/u/0/folders/1HMd1N71l0SbDMvvSK4_b0JrNZ6IoktHE).

**Comment by lwrubel** [comment]
**Question 2: Establish a baseline for open access publication by Stanford authors**
- a. What proportion of Stanford publications are OA vs. non-OA?
(Dimensions: # of items with open_access = oa_all vs. # of items with open_access = closed)
- b. What is the distribution of Stanford OA publications across different OA pathways?
(Dimensions: distribution of values in open_access (gold vs. green vs. hybrid vs. bronze))
(Dimensions: # of items with open_access = oa_all AND type = preprint)
(Dimensions: # of items with pmcid = not null)
(Dimensions: # of items with arxiv_id = not null)
- c. Where are green OA Stanford publications being made available?

**Question 3: Identify potential opportunities to increase open access publication by Stanford authors**
- a. How does the proportion of OA vs. non-OA Stanford publications vary between disciplines?
(Dimensions: Divide items by ANZRC FOR classification and count open_access = oa_all vs. # of items with open_access = closed within each classification)
(Calculate for both ANZRC FOR a) ‘Division’ (top level) and b) ‘Group’ (mid level) classifications (‘Field’ level is probably too granular for our purposes))
- b. How does the proportion of OA vs. non-OA Stanford publications vary between departments, schools, institutes, and/or centers?
[requires Stanford-specific data that may not be available at this time]
Note that for academic council members (see next query below), we have verified information about school and department affiliation, so to the extent we can match authors, we can easily run a school and/or department breakdown on their publications
- c. What proportion of Stanford publications are covered by the current OA policy? 
Dimensions: # of items with
date = December 2020-present, AND
type = ‘article’, AND
author contains an author on the list of Academic Council members (or match via disambiguated authors in researchers field)
- d. What proportion of Stanford publications covered by the current OA policy are currently OA and through which OA pathway?
Dimensions: # of items returned for previous query with open_access = oa_all 
Dimensions: # of items returned for previous query with distribution of values in open_access (gold vs. green vs. hybrid vs. bronze)
- e. What proportion of Stanford publications do NOT include an author on the Academic Council?
Dimensions: # of items for which no values in author match an author on the list of Academic Council members
[is it possible to obtain information about status of non-Academic Council Stanford authors - i.e. are they post-docs, graduate students, undergraduates, etc.?]

**Comment by edsu** [comment]
I believe that these questions are now answered in: https://github.com/sul-dlss-labs/open-access-stanford/blob/main/Report.ipynb
