### ISSUE TITLE
Move questions 4 and 5 to Colab notebook

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss-labs/rialto-scripts#23]
Questions 4 and 5 both deal with Funding questions; it makes sense to group them in one Colab notebook.

The initial questions from Rochelle are [here](https://docs.google.com/document/d/1VQooV2hzN0q_HYJQClPQh5rKPZLr00jd-jsIOSxNDcE/edit#heading=h.ca158ssm5vbf).

The dashboard pages that try to answer those questions are 4 and 5  [here](https://sul-dlss-labs-rialto-scripts-oa-dashboardoa-dashboard-yiuiox.streamlit.app/).

You can work in [this notebook](https://colab.research.google.com/drive/1cwSvkVVSkBAkS0BRcvHOJPypY9jViBwT).

The starting data file is [here](https://drive.google.com/drive/u/0/folders/1HMd1N71l0SbDMvvSK4_b0JrNZ6IoktHE).

**Comment by edsu** [comment]
Here are the questions, just to have them here:

### Q4) Identify potential opportunities to decrease the time, effort, and money spent on open access publication by Stanford authors: 
* How much do Stanford authors spend to publish OA?
  * Dimensions: # of items with open_access =  gold OA OR hybrid OA 
    * Rough Estimate: Multiply number in each category by average APC
      * $3,000 for Hybrid 
      * $1,000 for Gold 
    * Precision Estimate: Retrieve journal-specific APCs for each publication via [DOAJ API](https://www.doaj.org/api/v3/docs) or[ OpenAlex](https://docs.openalex.org/api-entities/sources)
* How much would Stanford have spent to publish all articles Gold or Hybrid OA?
  * Total # of Stanford publications
    *  Rough Estimate: Multiply number in each category by average APC
      * $3,000 for Hybrid 
      * $1,000 for Gold 
    * Precision Estimate: Retrieve journal-specific APCs for each publication via [DOAJ API](https://www.doaj.org/api/v3/docs) or[ OpenAlex](https://docs.openalex.org/api-entities/sources)

### Q5) Evaluate how Stanford research publication activities are likely to be affected by approaching changes in funder and publisher research access policies
* To what extent do Stanford publications rely on grant funding?
  * [Dimensions: # of items with grant_id = not null](https://colab.research.google.com/drive/1izFDXcqfcXJpDRjan8dc-piTCGmXbUKn#scrollTo=uxARw4VbtaNy&line=1&uniqifier=1)
    * [this won’t be a perfect measure of grant funding but from reviewing the field values in the sample does seem likely to capture U.S. government and major private funders with OA policies]
* What volume of Stanford publications rely on funding from U.S. federal agencies?
  * Dimensions: # of items with grant_id = not null AND funders contains at least one value that is also within ‘US Federal Funders’ group in Dimensions’ [‘Funder Groups](https://docs.dimensions.ai/dsl/datasource-funder_groups.html)’ filter
* What proportion of funders supporting Stanford publications have or will soon have open or public access mandates?
  * Dimensions: # of items with grant_id = not null AND funders contains at least one value that 
    * is also within ‘US Federal Funders’ group in Dimensions’ [‘Funder Groups](https://docs.dimensions.ai/dsl/datasource-funder_groups.html)’ filter, OR
    * matches a list of funders with known OA policies

**Comment by edsu** [comment]
@jacobthill I've got these questions moved to the notebook in google drive now. I would like to put a copy here as well in case something goes wrong in Drive. Does that sound ok?
